local abilities = {
  ["Casual Hero"] = {{Name = 'Serious Squirt Gun', Upgrades = 10, Form = 2}, {Name = 'Serious Punch', Upgrades = 10, Form = 2}},
  ["King of Heroes"] = {{Name = 'Enuma Elish', Upgrades = 10, Form = 3}, {Name = 'Vinama', Upgrades = 10, Form = 3}},
  ["Nightmare"] = {{Name = 'Aleph', Upgrades=12, Form = 1}, {Name = 'Bet', Upgrades=12, Form = 1}, {Name = 'Gimel', Upgrades=12, Form = 1}, {Name = 'Dalet', Upgrades=12, Form = 1}, {Name = 'Hei', Upgrades=12, Form = 1}, {Name = 'Vav', Upgrades=12, Form = 1}, {Name = 'Zayin', Upgrades=12, Form = 1}, {Name = 'Het', Upgrades=12, Form = 1}, {Name = 'Tet', Upgrades=12, Form = 1}, {Name = 'Yud', Upgrades=12, Form = 1}, {Name = 'Yud Aleph', Upgrades=12, Form = 1}, {Name = 'Yud Bet', Upgrades=12, Form = 1}},
  ["Shining Star Idol"] = {{Name = 'Idol Buff', Upgrades=1, Form = 1}},
}

return abilities;
