local maps = {
-- Story
['Large Village'] = {Story = true},
['Hollow Land'] = {Story = true},
['Monster City'] = {Story = true},
['Academy Demon'] = {Story = true},
-- Raid
['Lawless City'] = {Raid = true},
['Temple'] = {Raid = true},
['Orc Castle'] = {Raid = true},
['Kingdom of Wandenreich'] = {Raid = true},
['Namakora Village'] = {Raid = true},
['Central Command'] = {Raid = true},
['The Crimson Eclipse'] = {Raid = true},
['Hidden Leaf Village'] = {Raid = true},
-- Portal
['Jeju Island'] = {Por = true},
['Namek Planet'] = {Por = true},
-- Tower
['Cursed Place'] = {T = true},
['The Lost Ancient World'] = {T = true},
-- ?
['Cog Dimensions'] = {Misc = true},
['Moonbase Sci-Fi'] = {Misc = true},
['The Forest'] = {Misc = true},
['Crystal Mine'] = {Misc = true},
['Vampire Castle Act'] = {Misc = true},
['Nazarick Mausoleum'] = {Misc = true},
-- Worldline
['Double Dungeon'] = {WL = true},
['Double Dungeon 2'] = {WL = true},
['Lingxian Academy'] = {WL = true},
['Lingxian Yard'] = {WL = true},
-- Event
['Verdant Shroud'] = {E = true},
['Lunaris Isle'] = {E = true},
['Steel Ball Run'] = {E = true},
['Frontline Command Post'] = {E = true},
['Easter Event'] = {E = true},
['Summer Beach'] = {E = true},
};

return maps
