local abilities = {
    --Godly
    FrierenGodly = {{Name = "Mage's Staff", Upgrades=0}, {Name = 'Black Hole', Upgrades=13}, {Name = 'Ancient Golem', Upgrades=12}, {Name = 'Mastered Zeltreck', Upgrades=8}},
    GilgameshGodly = {{Name = 'Enomo Olis', Upgrades=9}, {Name = 'Combined Noble Special: Enomo Olis', Upgrades=12}},
    ShinraGodly = {Neutral = {{Name = 'Fabric of Reality', Upgrades=12}}, Dark = {{Name = 'Despair', Upgrades=12}}, Light = {{Name = 'Lightning Shower', Upgrades=12}}, Fire = {{Name = 'Volcanic Eruption', Upgrades=12}}, Nature = {{Name = 'Purification of Life', Upgrades=12}}, Water = {{Name = 'Ice Terrain', Upgrades=12}}},
    CosmicGarou = {{Name = 'Galactic Destroyer', Upgrades=11}, {Name = 'Serious Punch', Upgrades=11}},
    LuffyG5 = {{Name = 'Ultimate Gun', Upgrades=13}},
    SungMonarch = {{Name = 'System', Upgrades=0}, {Name = 'Shadow Index', Upgrades=6}, {Name = 'Cup Of Rebirth', Upgrades=14}},
    JinMoriGodly = {{Name = 'Nirvana', Upgrades=10}},
    GokuMUI = {{Name = 'Divine Avatar', Upgrades=12}, {Name = 'Final Spiritual Bomb', Upgrades=13}},
    Mugetsu = {{Name = 'Kai Release', Upgrades=0}},
    ['Dio Over Heaven'] = {{Name = 'Road Roller', Upgrades=11}, {Name = 'Over Heaven Special', Upgrades=13}},
    SukunaGodly = {{Name = 'Divine Flames', Upgrades=11}, {Name = 'Evil Shrine', Upgrades=12}, {Name = 'World Cutting Slash', Upgrades=13}},
    EscanorGodly = {{Name = 'The One Ultimate', Upgrades=11}},
    --EZA
    GojoEvo2EZA = {{Name = 'Unlimited Void', Upgrades=3}, {Name = 'Purple: MAXIMUM EX', Upgrades=11}},
    --Normal
    --61
    FernEvo = {{Name = 'Zeltreck', Upgrades=0}, {Name = 'Protective Blessing', Upgrades=10}},
    HarribelEvo = {{Name = 'Tsunami', Upgrades=9}},
    --60
    DanteEvo = {{Name = 'Hot Swap', Upgrades=13}, {Name = 'Fire Devil Trigger', Upgrades=0}},
    VirgilEvo = {{Name = 'Dimensional Breaker', Upgrades=13}, {Name = 'Lightning Devil Trigger', Upgrades=0}},
    TanjiroEvo2 = {{Name = 'Honokomi Koguro', Upgrades=11}},
    --59
    CIDEvo2 = {{Name = 'Mini Atomic', Upgrades=13}, {Name = 'Final Atomic', Upgrades=14}},
    LawEvo2 = {{Name = 'ROOM!!!', Upgrades=9}},
    ErzaEvo2 = {{Name = 'Fairy Armor', Upgrades=12}},
    DoflamingoEvo2 = {{Name = 'Birdcage', Upgrades=9}},
    MeguminEvo = {{Name = 'Mini Expluoshun', Upgrades=0}, {Name = 'Very Big Expluoshun', Upgrades=10}, {Name = 'FINAL EXPLUOSHUN!!!', Upgrades=10}},
    WanoNamiEvo = {{Name = 'Weather Shift', Upgrades=11}},
    --58
    GokuVegetaBlue = {{Name = 'Super Blue Fusion', Upgrades=12}},
    --57 CSW
    AkiEvo = {{Name = 'Fox Demon', Upgrades=10}, {Name = 'Cursed Mode', Upgrades=12}},
    MakimaEvo = {{Name = 'Domination', Upgrades=8}, {Name = 'Sacrifices', Upgrades=14}, {Name = 'Steal: 1000 Years', Upgrades=15}},
    PowerTrueDevil = {{Name = 'Blood Explosion', Upgrades=12}},
    RezeEvo = {{Name = 'Self Destruct', Upgrades=13}},
    --56 Pre-Summer
    AngelEvo = {{Name = 'Time Thief', Upgrades=10}, {Name = '10 Years', Upgrades=10}, {Name = '100 Years', Upgrades=11}, {Name = '1000 Years', Upgrades=12}},
--    BuddhaEvo = {{Name = 'Six Domains', Upgrades=14}, {Name = 'Sword of Zero', Upgrades=14}},
    MeliodasAssault = {{Name = 'Full Parry', Upgrades=11}, {Name = 'Assault Sword', Upgrades=12}},
    --55 SJK
    YutaEvo = {{Name = 'Heavenly Ladder', Upgrades=11}, {Name = 'Heavenly Ladder: MAXIMUM', Upgrades=11}, {Name = 'Pure Love', Upgrades=12}, {Name = 'Unmastered Purple', Upgrades=12}, {Name = 'Unmastered Void', Upgrades=12}},
    ItadoriShrine = {{Name = 'Resilient Shrine', Upgrades=11}},
    HiguramaEvo = {{Name = 'Judgement', Upgrades=11}},
    GetoEvo = {{Name = 'Uzumaki', Upgrades=8}, {Name = 'Uzumaki (MAXIMUM)', Upgrades=9}, {Name = 'Body Thief', Upgrades=10}},
    KashimoEvo = {{Name = 'Lightning Beast', Upgrades=11}},
    --54
    Kale_Caulifla = {{Name = 'Sisters Fusion', Upgrades=7}},
    KelfaFusion = {{Name = 'Sisters Super Transformation', Upgrades=5}},
    KelfaFusion2 = {{Name = 'Fusion Overdrive', Upgrades=6}},
    ShisuiEvo = {{Name = 'Kotoamatsukami: Halt', Upgrades=13}, {Name = 'Kotoamatsukami: Reverse', Upgrades=13}},
    --53 FGO
    MedusaFateEvo = {{Name = 'Ballarofone', Upgrades=11}},
    IshtarEvo = {{Name = 'Venus Judgement', Upgrades=8}},
    SaberCasterEvo = {{Name = 'Bells', Upgrades=2}, {Name = 'Noble Special: Flower Garden', Upgrades=10}},
    --52 BC
    AstaImperial = {{Name = "King's Sword Finisher", Upgrades=11}},
    JuliasEvo = {{Name = 'Time Vault', Upgrades=12}},
    Giorno_GER = {{Name = 'Zero', Upgrades=8}},
    ['Dio Greatest High'] = {{Name = 'Za Warudo!', Upgrades=9}},
    CID = {{Name = 'I AM ATOMIC!', Upgrades=7}},
    CIDEvo = {{Name = 'Celestial Strike', Upgrades=9}},
    --BP/Ex
    B2Evo = {{Name = 'Self Destruction', Upgrades = 11}},
    B2EvoShiny = {{Name = 'Self Destruction', Upgrades = 11}},
    --Farm
    AiHoshinoEvo = {{Name = 'Concert', Upgrades=6}},
    --Special
    GodlyEnkidu = {{Name = 'Enomo Olis: Bloom', Upgrades=8}},
    Rika_Summon = {{Name = 'Beam of Love', Upgrades=0}},
    GokuVegetaFusion = {{Name = 'Spirit Finisher', Upgrades=11}, {Name = 'Final Energy Beam', Upgrades=12}},
}

return abilities;
