local abilities = {
    --Godly
    FrierenGodly = {{Name = "Mage\226\128\153s Staff", Upgrades=0}, {Name = 'Black Hole', Upgrades=13}, {Name = 'Ancient Golem', Upgrades=12}, {Name = 'Mastered Zeltreck', Upgrades=8}},
    FrierenGodlyShiny = {{Name = "Mage\226\128\153s Staff", Upgrades=0}, {Name = 'Black Hole', Upgrades=13}, {Name = 'Ancient Golem', Upgrades=12}, {Name = 'Mastered Zeltreck', Upgrades=8}},
    GilgameshGodly = {{Name = 'Enomo Olis', Upgrades=9}, {Name = 'Combined Noble Special: Enomo Olis', Upgrades=12}},
    ShinraGodly = {Neutral = {{Name = 'Fabric of Reality', Upgrades=12}}, Dark = {{Name = 'Despair', Upgrades=12}}, Light = {{Name = 'Lightning Shower', Upgrades=12}}, Fire = {{Name = 'Volcanic Eruption', Upgrades=12}}, Nature = {{Name = 'Purification of Life', Upgrades=12}}, Water = {{Name = 'Ice Terrain', Upgrades=12}}},
    CosmicGarou = {{Name = 'Galactic Destroyer', Upgrades=11}, {Name = 'Serious Punch', Upgrades=11}},
    LuffyG5 = {{Name = 'Ultimate Gun', Upgrades=13}},
    SungMonarch = {{Name = 'System', Upgrades=0}, {Name = 'Shadow Index', Upgrades=6}, {Name = 'Cup Of Rebirth', Upgrades=14}},
    JinMoriGodly = {{Name = 'Nirvana', Upgrades=10}},
    GokuMUI = {{Name = 'Divine Avatar', Upgrades=12}, {Name = 'Final Spiritual Bomb', Upgrades=13}},
    Mugetsu = {{Name = 'Kai Release', Upgrades=0}},
    ['Dio Over Heaven'] = {{Name = 'Road Roller', Upgrades=11}, {Name = 'Over Heaven Special', Upgrades=13}},
    SukunaGodly = {{Name = 'Divine Flames', Upgrades=11}, {Name = 'Evil Shrine', Upgrades=12}, {Name = 'World Cutting Slash', Upgrades=13}},
    EscanorGodly = {{Name = 'The One Ultimate', Upgrades=11}},
    --EZA
    GojoEvo2EZA = {
        { Name = "Unlimited Void", Upgrades = 3, MaxUpgrade = 10 }, 
        { Name = "Limitless Void",   Upgrades = 11 },
        { Name = "Purple: MAXIMUM EX", Upgrades = 11 }
    },
    GilgameshEvoEZA = {{Name = 'Enhanced Heavenly Sword', Upgrades=10}},
    DarkSaberEZA = {{Name = 'Dark Corruption', Upgrades=9}, {Name = 'Corrupted Excalibur', Upgrades=10}},
    VegitoSSJBEZA = {{Name = 'Energy Beam', Upgrades=12}, {Name = 'Godly Energy Beam', Upgrades=14}},
    --Normal
    --61
    FernEvo = {{Name = 'Zeltreck', Upgrades=0}, {Name = 'Protective Blessing', Upgrades=10}},
    HarribelEvo = {{Name = 'Tsunami', Upgrades=9}},
    --60
    DanteEvo = {{Name = 'Hot Swap', Upgrades=13}, {Name = 'Fire Devil Trigger', Upgrades=0}},
    VirgilEvo = {{Name = 'Dimensional Breaker', Upgrades=13}, {Name = 'Lightning Devil Trigger', Upgrades=0}},
    TanjiroEvo2 = {{Name = 'Honokomi Koguro', Upgrades=11}},
    --59
    CIDEvo2 = {{Name = 'Mini Atomic', Upgrades=13}, {Name = 'Final Atomic', Upgrades=14}},
    LawEvo2 = {{Name = 'ROOM!!!', Upgrades=9}},
    ErzaEvo2 = {{Name = 'Fairy Armor', Upgrades=12}},
    DoflamingoEvo2 = {{Name = 'Birdcage', Upgrades=9}},
    MeguminEvo = {{Name = 'Mini Expluoshun', Upgrades=0}, {Name = 'Very Big Expluoshun', Upgrades=10}, {Name = 'FINAL EXPLUOSHUN!!!', Upgrades=10}},
    WanoNamiEvo = {{Name = 'Weather Shift', Upgrades=11}},
    --58
    GokuVegetaBlue = {{Name = 'Super Blue Fusion', Upgrades=12}},
    --57 CSW
    AkiEvo = {{Name = 'Fox Demon', Upgrades=10}, {Name = 'Cursed Mode', Upgrades=12}},
    MakimaEvo = {{Name = 'Domination', Upgrades=8}, {Name = 'Sacrifices', Upgrades=14}, {Name = 'Steal: 1000 Years', Upgrades=15}},
    PowerTrueDevil = {{Name = 'Blood Explosion', Upgrades=12}},
    RezeEvo = {{Name = 'Self Destruct', Upgrades=13}},
    --56 Pre-Summer
    AngelEvo = {{Name = 'Time Thief', Upgrades=10}, {Name = '10 Years', Upgrades=10}, {Name = '100 Years', Upgrades=11}, {Name = '1000 Years', Upgrades=12}},
--    BuddhaEvo = {{Name = 'Six Domains', Upgrades=14}, {Name = 'Sword of Zero', Upgrades=14}},
    MeliodasAssault = {{Name = 'Full Parry', Upgrades=11}, {Name = 'Assault Sword', Upgrades=12}},
    --55 SJK
    YutaEvo = {{Name = 'Heavenly Ladder', Upgrades=11}, {Name = 'Heavenly Ladder: MAXIMUM', Upgrades=11}, {Name = 'Pure Love', Upgrades=12}, {Name = 'Unmastered Purple', Upgrades=12}, {Name = 'Unmastered Void', Upgrades=12}},
    ItadoriShrine = {{Name = 'Resilient Shrine', Upgrades=11}},
    HiguramaEvo = {{Name = 'Judgement', Upgrades=11}},
    GetoEvo = {{Name = 'Uzumaki', Upgrades=8}, {Name = 'Uzumaki (MAXIMUM)', Upgrades=9}, {Name = 'Body Thief', Upgrades=10}},
    KashimoEvo = {{Name = 'Lightning Beast', Upgrades=11}},
    --54
    Kale_Caulifla = {{Name = 'Sisters Fusion', Upgrades=7}},
    KelfaFusion = {{Name = 'Sisters Super Transformation', Upgrades=5}},
    KelfaFusion2 = {{Name = 'Fusion Overdrive', Upgrades=6}},
    ShisuiEvo = {{Name = 'Kotoamatsukami: Halt', Upgrades=13}, {Name = 'Kotoamatsukami: Reverse', Upgrades=13}},
    --53 FGO
    MedusaFateEvo = {{Name = 'Ballarofone', Upgrades=11}},
    IshtarEvo = {{Name = 'Venus Judgement', Upgrades=8}},
    SaberCasterEvo = {{Name = 'Bells', Upgrades=2}, {Name = 'Noble Special: Flower Garden', Upgrades=10}},
    --52 BC
    AstaImperial = {{Name = "King's Sword Finisher", Upgrades=11}},
    JuliasEvo = {{Name = 'Time Vault', Upgrades=12}},
    --51 Easter
    MadokaEvo = {{Name = 'You Shall Never Despair', Upgrades=11}},
    AkameEvo = {{Name = "Marasame's Curse", Upgrades=11}},
    BrunoEvo = {{Name = 'Zipper Dissection', Upgrades=10}},
    --50
    WangLingEvo = {{Name = 'World Rewind', Upgrades=11}, {Name = 'Reality Sword', Upgrades=12}, {Name = 'Erase Existence', Upgrades=12}},
    AnosEvo = {{Name = '7 Step Destruction', Upgrades=12}},
    ChihiroEvo = {{Name = 'Cloud Sword', Upgrades=11}},
    --49 Fire Force
    BenimaruEvo = {{Name = 'Perfect Pyrokenesis', Upgrades=11}},
    ShinraAdolla = {{Name = 'Allado Burst', Upgrades=11}},
    ArthurStarRing = {{Name = 'Elemental Power', Upgrades=12}, {Name = 'Execution', Upgrades=12}, {Name = 'Worthiness', Upgrades=12}},
    --48 Saint Patrick
    KiritoStarKing = {{Name = 'Release', Upgrades=12}},
--    ShirouEvo
    --47 Blue Cock
    IsagiEvo = {{Name = 'Luck', Upgrades=11}},
    ShidouEvo = {{Name = 'Ultimate Drive', Upgrades=10}},
    --46 Godly QoL
    Homura = {{Name = 'Time Control', Upgrades=0}},
    --45 OPM
    DamagedSaitama = {{Name = 'Serious Sneeze', Upgrades=11}},
    TatsumakiEvo = {{Name = 'Psychic Hurricane', Upgrades=10}},
    --44 Valentine P2
    RogerEvo = {{Name = 'Celestial Rend', Upgrades=10}},
    --43 Valentine P1
    MitsuriEvo = {{Name = "Swordswoman's Mark", Upgrades=11}},
    IsseiEvo = {{Name = 'BOOST!', Upgrades=9}},
    YoruichiEvo = {{Name = 'Thunder Goddess', Upgrades=10}},
    --42 OP
    KaidoHybrid = {{Name = "Plasmatic Burst", Upgrades=10}},
    --41 1st Anniversary
    BeastGohanEvo = {{Name = 'Everything Into One Shot', Upgrades=12}},
    SubaruEvo = {{Name = 'Death Return', Upgrades=0}, {Name = 'Future Recall', Upgrades=9}},
    --40 AoT
    ErenEvo = {{Name = 'Berserk Giant', Upgrades=9}, {Name = 'Coordinate Resonance', Upgrades=10}},
    ReinerEvo = {{Name = 'Armored Protection', Upgrades=8}},
    ErwinEvo = {{Name = "Leader's Influence", Upgrades=1}, {Name = 'Final Speech', Upgrades=2}},
    --37 Great Ninja War
    MadaraSixPath = {{Name = 'Everlasting Illusion', Upgrades=11}, {Name = 'Armored Warrior', Upgrades=12}},
    ObitoSixPath = {{Name = 'Path Displacement', Upgrades=9}},
    MaitoGaiGates = {{Name = 'Last Resort', Upgrades=11}},
    --35 Godly Rush
    Ainz = {{Name = 'Death to ALL!', Upgrades=6}},
    Giorno_GER = {{Name = 'Zero', Upgrades=8}},
    Rudeus = {{Name = 'XL-Healing', Upgrades=6}},
    --34 Fate
    GilgameshEvo = {{Name = 'Heavenly Sword', Upgrades=10}},
    DarkSaber = {{Name = 'Victory Blade', Upgrades=9}},
    --33 QoL
    VegitoSSJB = {{Name = 'Final Blast', Upgrades=10}},
    RengokuDemon = {{Name = 'Demon Burst', Upgrades=10}},
    ByakuyaEvo = {{Name = 'SenbonKat', Upgrades=10}},
    WhiteBreadEvo = {{Name = 'Quake Wave', Upgrades=10}},
    ['Dio Greatest High'] = {{Name = 'Za Warudo!', Upgrades=9}},
    CID = {{Name = 'I AM ATOMIC!', Upgrades=7}},
    CIDEvo = {{Name = 'Celestial Strike', Upgrades=9}},
    --BP/Ex
    B2Evo = {{Name = 'Self Destruction', Upgrades = 11}},
    B2EvoShiny = {{Name = 'Self Destruction', Upgrades = 11}},
    Lancer = {{Name = 'Gaí Bolgé', Upgrades=8}},
    LancerShiny = {{Name = 'Gaí Bolgé', Upgrades=8}},
    --Farm
    AiHoshinoEvo = {{Name = 'Concert', Upgrades=6}},
    --Special
    GodlyEnkidu = {{Name = 'Enomo Olis: Bloom', Upgrades=8}},
    Rika_Summon = {{Name = 'Beam of Love', Upgrades=0}},
    GokuVegetaFusion = {{Name = 'Spirit Finisher', Upgrades=11}, {Name = 'Final Energy Beam', Upgrades=12}},
}

return abilities;
