local abilities = {
    --Godly
    FrierenGodly = { {"Mage's Staff", UPReq=0}, {"Black Hole", UPReq=0}, {"Ancient Golem", UPReq=0}, {"Mastered Zeltreck", UPReq=0}},
    GilgameshGodly = {{"Enomo Olis", UPReq=0}, {"Combined Noble Special: Enomo Olis", UPReq=0}},
    ShinraGodly = {Neutral = {{"Fabric of Reality", UPReq=0}}, Dark = {{"Despair", UPReq=0}}, Light = {{"Lightning Shower", UPReq=0}}, Fire = {{"Volcanic Eruption", UPReq=0}}, Nature = {{"Purification of Life", UPReq=0}}, Water = {{"Ice Terrain", UPReq=0}} },
    CosmicGarou = {{"Galactic Destroyer", UPReq=0}, {"Serious Punch", UPReq=0}},
    LuffyG5 = {{"Ultimate Gun", UPReq=0}},
    SungMonarch = {{"System", UPReq=0}, {"Shadow Index", UPReq=0}, {"Cup Of Rebirth", UPReq=0}},
    JinMoriGodly = {{"Nirvana", UPReq=0}},
    GokuMUI = {{"Divine Avatar", UPReq=0}, {"Final Spiritual Bomb", UPReq=0}},
    Mugetsu = {{"Kai Release", UPReq=0}},
    ['Dio Over Heaven'] = {{"Road Roller", UPReq=0}, {"Over Heaven Special", UPReq=0}},
    SukunaGodly = {{"Divine Flames", UPReq=0}, {"Evil Shrine", UPReq=0}, {"World Cutting Slash", UPReq=0}},
    EscanorGodly = {{"The One Ultimate", UPReq=0}},
    --EZA
    GojoEvo2EZA = {{"Unlimited Void", UPReq=0}, {"Purple: MAXIMUM EX", UPReq=0}},
    --Casual
    CIDEvo2 = {{"Mini Atomic", UPReq=0}, {"Final Atomic", UPReq=0}},
    LawEvo2 = {{"ROOM!!!", UPReq=0}},
    AstaImperial = {{"King's Sword Finisher", UPReq=0}},
    --Farm
    AiHoshinoEvo = {{"Concert", UPReq=6}},
    --Special
    GodlyEnkidu = {{"Enomo Olis: Bloom", UPReq=0}},
    GokuVegetaFusion = {{"Spirit Finisher", UPReq=0}, {"Final Energy Beam", UPReq=0}},
}

return abilities;
