local abilities = {
    --Godly
    FrierenGodly = { {"Mage's Staff", Upgrades=0}, {"Black Hole", Upgrades=0}, {"Ancient Golem", Upgrades=0}, {"Mastered Zeltreck", Upgrades=0}},
    GilgameshGodly = {{"Enomo Olis", Upgrades=0}, {"Combined Noble Special: Enomo Olis", Upgrades=0}},
    ShinraGodly = {Neutral = {{"Fabric of Reality", Upgrades=0}}, Dark = {{"Despair", Upgrades=0}}, Light = {{"Lightning Shower", Upgrades=0}}, Fire = {{"Volcanic Eruption", Upgrades=0}}, Nature = {{"Purification of Life", Upgrades=0}}, Water = {{"Ice Terrain", Upgrades=0}} },
    CosmicGarou = {{"Galactic Destroyer", Upgrades=0}, {"Serious Punch", Upgrades=0}},
    LuffyG5 = {{"Ultimate Gun", Upgrades=0}},
    SungMonarch = {{"System", Upgrades=0}, {"Shadow Index", Upgrades=0}, {"Cup Of Rebirth", Upgrades=0}},
    JinMoriGodly = {{"Nirvana", Upgrades=0}},
    GokuMUI = {{"Divine Avatar", Upgrades=0}, {"Final Spiritual Bomb", Upgrades=0}},
    Mugetsu = {{"Kai Release", Upgrades=0}},
    ['Dio Over Heaven'] = {{"Road Roller", Upgrades=0}, {"Over Heaven Special", Upgrades=0}},
    SukunaGodly = {{"Divine Flames", Upgrades=0}, {"Evil Shrine", Upgrades=0}, {"World Cutting Slash", Upgrades=0}},
    EscanorGodly = {{"The One Ultimate", Upgrades=0}},
    --EZA
    GojoEvo2EZA = {{"Unlimited Void", Upgrades=0}, {"Purple: MAXIMUM EX", Upgrades=0}},
    --Casual
    CIDEvo2 = {{"Mini Atomic", Upgrades=0}, {"Final Atomic", Upgrades=0}},
    LawEvo2 = {{"ROOM!!!", Upgrades=0}},
    AstaImperial = {{"King's Sword Finisher", Upgrades=0}},
    --Farm
    AiHoshinoEvo = {{"Concert", Upgrades=6}},
    --Special
    GodlyEnkidu = {{"Enomo Olis: Bloom", Upgrades=0}},
    GokuVegetaFusion = {{"Spirit Finisher", Upgrades=0}, {"Final Energy Beam", Upgrades=0}},
}

return abilities;
