local abilities = {
    --Godly
    FrierenGodly = {{Name = "Mage's Staff", Upgrades=0}, {Name = 'Black Hole', Upgrades=0}, {Name = 'Ancient Golem', Upgrades=0}, {Name = 'Mastered Zeltreck', Upgrades=0}},
    GilgameshGodly = {{Name = 'Enomo Olis', Upgrades=0}, {Name = 'Combined Noble Special: Enomo Olis', Upgrades=0}},
    ShinraGodly = {Neutral = {{Name = 'Fabric of Reality', Upgrades=0}}, Dark = {{Name = 'Despair', Upgrades=0}}, Light = {{Name = 'Lightning Shower', Upgrades=0}}, Fire = {{Name = 'Volcanic Eruption', Upgrades=0}}, Nature = {{Name = 'Purification of Life', Upgrades=0}}, Water = {{Name = 'Ice Terrain', Upgrades=0}} },
    CosmicGarou = {{Name = 'Galactic Destroyer', Upgrades=0}, {Name = 'Serious Punch', Upgrades=0}},
    LuffyG5 = {{Name = 'Ultimate Gun', Upgrades=0}},
    SungMonarch = {{Name = 'System', Upgrades=0}, {Name = 'Shadow Index', Upgrades=0}, {Name = 'Cup Of Rebirth', Upgrades=0}},
    JinMoriGodly = {{Name = 'Nirvana', Upgrades=0}},
    GokuMUI = {{Name = 'Divine Avatar', Upgrades=0}, {Name = 'Final Spiritual Bomb', Upgrades=0}},
    Mugetsu = {{Name = 'Kai Release', Upgrades=0}},
    ['Dio Over Heaven'] = {{Name = 'Road Roller', Upgrades=0}, {Name = 'Over Heaven Special', Upgrades=0}},
    SukunaGodly = {{Name = 'Divine Flames', Upgrades=0}, {Name = 'Evil Shrine', Upgrades=0}, {Name = 'World Cutting Slash', Upgrades=0}},
    EscanorGodly = {{Name = 'The One Ultimate', Upgrades=0}},
    --EZA
    GojoEvo2EZA = {{Name = 'Unlimited Void', Upgrades=0}, {Name = 'Purple: MAXIMUM EX', Upgrades=0}},
    --Casual
    CIDEvo2 = {{Name = 'Mini Atomic', Upgrades=0}, {Name = 'Final Atomic', Upgrades=0}},
    LawEvo2 = {{Name = 'ROOM!!!', Upgrades=0}},
    AstaImperial = {{Name = "King's Sword Finisher", Upgrades=0}},
    --Farm
    AiHoshinoEvo = {{Name = 'Concert', Upgrades=0}},
    --Special
    GodlyEnkidu = {{Name = 'Enomo Olis: Bloom', Upgrades=0}},
    GokuVegetaFusion = {{Name = 'Spirit Finisher', Upgrades=0}, {Name = 'Final Energy Beam', Upgrades=0}},
}

return abilities;
